### ISSUE TITLE
Empty file created with example mindmap

### ISSUE THREAD

**Issue by micgro42** [boolaz/mm2doku#2]
With the given mindmap `1-freemind_lamp.mm` an empty outputfile is created.
The call was:

``` bash
python2 mm2doku.py 1-freemind_lamp.mm temp.txt
```

Output of 

``` bash
python2 --version
```

is

```
Python 2.7.12
```

**Comment by boolaz** [comment]
Weird. Normally this file is supposed to work without any issue.
We're gonna investigate together.
Which OS ? windows ? linux ? Mac ?

**Comment by micgro42** [comment]
Arch Linux: 

```
%> uname -orsm 
Linux 4.7.2-1-ARCH x86_64 GNU/Linux

%> lsb_release -a    
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:    rolling
Codename:   n/a
```

**Comment by boolaz** [comment]
Okay. I have absolutely no pb on Ubuntu with the same version of python.
I'm going to install a fresh Arch linux VM and check what could cause this problem.
Thanks for your feedback

**Comment by micgro42** [comment]
I'll gladly help. Is there a debug flag or something that I could use to get an more verbose output?

I"ll try it at home with another Arch Linux and a Debian and then report the results here.

**Comment by boolaz** [comment]
Thanks for your help
just tested it on kali rolling, it works.
I install arch Linux right away.
Stay tuned ...

**Comment by boolaz** [comment]
I downloaded an ArchLinux VM from http://www.osboxes.org/arch-linux/ 
- VMware (VMDK) 32bit (Linux 4.7.0-1-ARCH i686 GNU/Linux)
- (SHA256: 1e0e74f3254a284dcdd159147455478a0d21538f74c0a1c40feb3e85393b6341)

Via PACMAN, i installed python2 and git :

```
pacman -S python2-numpy
pacman -S git
```

then I cloned the mm2doku project :
`git clone https://github.com/boolaz/mm2doku`

Finally : 
`python2 mm2doku.py sample/1-freemind_lamp.mm sample.txt`

I got my file translated successfully

I didn't have to face any issue on my end. It your archlinux installation standard ? or did you customized it in some way it could cause problems to get python2 working fine ?

Can you try for me please, and tell me if you have at least a message ?
`python2 mm2doku.py --help`

Thanks

Bruno

**Comment by micgro42** [comment]
Mh, I tried it on the laptop at home - a more vanilla Arch Linux than the desktop at work - and it works. Strange. Maye it's some problem with my specifc setup at work after all.

Edit: And it works my Debian desktop as well. Seems to be a local problem at my end. Sorry for the noise.

**Comment by boolaz** [comment]
Okay, cool. good to hear then.
This is what I've been thinking too. This is possibly due to a custom setup on your distro.
I was successful at testing the tool with various releases of Linux distributions and I use no exotic libraries so normally It should work fine.
I'm always interested in a feedback if you find the reason why it doesn't work on your particular installation

Bruno
